version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: discord.js
    versions:
    - 12.5.2
  - dependency-name: release-it
    versions:
    - 14.5.1
  - dependency-name: "@discordjs/opus"
    versions:
    - 0.4.0
